"""Canonical Pydantic contracts shared across Vellum components."""

from __future__ import annotations

from datetime import datetime
from typing import Literal

from pydantic import BaseModel, Field


class Transaction(BaseModel):
    """Normalized transaction record ingested from external sources."""

    id: str
    source: Literal["plaid", "stripe", "manual"]
    amount_cents: int
    currency: str
    vendor_name: str
    vendor_normalized: str
    description: str
    occurred_at: datetime
    category: str | None = None
    raw: dict


class Action(BaseModel):
    """Action recommendation generated by one of the Vellum agents."""

    id: str
    action_type: Literal[
        "draft_email",
        "cancel_subscription",
        "request_clawback",
        "flag_for_review",
        "create_journal_entry",
    ]
    target: dict
    requires_approval: bool
    status: Literal["pending", "approved", "executed", "rejected"]


class Finding(BaseModel):
    """Structured finding emitted by an agent evaluation."""

    id: str
    agent: Literal[
        "ingestion",
        "reconciliation",
        "forensics",
        "compliance",
        "reporting",
    ]
    finding_type: str
    severity: Literal["info", "low", "medium", "high", "critical"]
    confidence: float = Field(ge=0.0, le=1.0)
    title: str = Field(max_length=80)
    summary: str
    evidence: list[dict]
    reasoning_trace: str
    suggested_actions: list[Action]
    created_at: datetime


class LedgerEntry(BaseModel):
    """Audit-ready ledger envelope for finding lifecycle state."""

    finding: Finding
    slack_message_ts: str | None = None
    approver: str | None = None
    audit_pack_id: str | None = None

